spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          group: product
          destination: shop2
          contentType: application/json
        output:
          destination: shop2
          contentType: application/json